# permissions for end users to view timezones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: timezone-viewer-role
rules:
- apiGroups:
  - wallclocks.ziglu.io
  resources:
  - timezones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wallclocks.ziglu.io
  resources:
  - timezones/status
  verbs:
  - get
