# permissions for end users to edit timezones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: timezone-editor-role
rules:
- apiGroups:
  - wallclocks.ziglu.io
  resources:
  - timezones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wallclocks.ziglu.io
  resources:
  - timezones/status
  verbs:
  - get
