# permissions for end users to view wallclocks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wallclock-viewer-role
rules:
- apiGroups:
  - wallclocks.ziglu.io
  resources:
  - wallclocks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wallclocks.ziglu.io
  resources:
  - wallclocks/status
  verbs:
  - get
